site_name: Clidantic
repo_url: https://github.com/edornd/clidantic
repo_name: edornd/clidantic
theme:
  name: material
  palette:
    - scheme: default
      primary: blue
      accent: amber
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: amber
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

nav:
  - Home: index.md
  - User Guide:
      - guide/intro.md
      - guide/fields.md
      - guide/primitives.md
      - guide/complex.md
      - guide/nesting.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - mdx_include
